language: node_js
node_js:
  - "8.1.2"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm update

script:
  - npm run build

after_success:
  - firebase deploy --non-interactive --token=${FIREBASE_TOKEN}