language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --non-interactive --token=${FIREBASE_TOKEN}